    
name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print a welcome message
        run: echo "Welcome to first GitHub Action workflow"

      - name: checkout repo  
        uses: actions/checkout@v4.2.2

      - name: list of repo files
        run: ls -la
